name: auto-release

on:
  push:
    branches:
      - main


jobs:
  auto-release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: auto release
        run: |
          git fetch --tags
          # Download a platform specific version of auto
          curl -kL -o - https://github.com/intuit/auto/releases/download/v10.28.0/auto-linux.gz | gunzip > ~/auto
          # Make auto executable
          chmod a+x ~/auto
          GH_TOKEN=${{secrets.GH_TOKEN}} ~/auto shipit -v