name: E2E Rollout Test

on:
  push:
    branches:
      - master
      - release-*
    tags:
      - v*
  workflow_dispatch: {}
  pull_request:
    branches:
      - master
      - release-*

env:
  # Common versions
  GO_VERSION: '1.17'
  GOLANGCI_VERSION: 'v1.38'
  KIND_VERSION: 'v0.7.0'
  KIND_IMAGE_VERSION: '[\"v1.20.7\"]'
  KIND_IMAGE_VERSIONS: '[\"v1.18.20\",\"v1.20.7\",\"v1.22.7\"]'

jobs:
  set-k8s-matrix:
    runs-on: ubuntu-20.04
    outputs:
      matrix: ${{ steps.set-k8s-matrix.outputs.matrix }}
    steps:
      - id: set-k8s-matrix
        run: |
          if [[ "${{ github.ref }}" == refs/tags/v* ]]; then
            echo "pushing tag: ${{ github.ref_name }}"
            echo "::set-output name=matrix::${{ env.KIND_IMAGE_VERSIONS }}"
          else
            echo "::set-output name=matrix::${{ env.KIND_IMAGE_VERSION }}"
          fi
  e2e-rollout-tests:
    runs-on: ubuntu-20.04
    needs: [ set-k8s-matrix ]
    if: needs.detect-noop.outputs.noop != 'true'
    strategy:
      matrix:
        k8s-version: ${{ fromJson(needs.set-k8s-matrix.outputs.matrix) }}

    steps:
      - name: Setup Kind
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: ${{ env.KIND_VERSION }}
          skipClusterCreation: true

      - name: Setup Kind Cluster
        run: |
          kind delete cluster
          kind create cluster --image kindest/node:${{ matrix.k8s-version }}
          kubectl version
          kubectl cluster-info