name: output matrix
on:
  pull_request:
    branches:
      - main
  push:
    tags:
      - v*
    branches:
      - main
jobs:

  set-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{steps.set-matrix.outputs.matrix}}
    steps:
      - name: Set matrix
        id: set-matrix
        run: |
          if [[ "${{ github.ref }}" == refs/tags/v* ]]; then
            echo "pushing tag: ${{ github.ref_name }}"
            echo "::set-output name=matrix::[\"one-test\", \"two-test\"]"
          else
            echo "::set-output name=matrix::[\"one-test\"]"
          fi

  get:
    runs-on: ubuntu-20.04
    needs: set-matrix
    strategy:
      matrix:
        subdir: ${{fromJson(needs.set-matrix.outputs.matrix)}}
    steps:
      - run: echo ${{ matrix.subdir }}
        name: subdir
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  get-again:
    runs-on: ubuntu-20.04
    needs: set-matrix
    strategy:
      matrix:
        subdir: ${{fromJson(needs.set-matrix.outputs.matrix)}}
    steps:
      - run: echo ${{ matrix.subdir }}
        name: subdir
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
