name: output matrix
on:
  pull_request:
    branches:
      - main
  push:
    tags:
      - v*
    branches:
      - main
jobs:

  set-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{steps.set-matrix.outputs.matrix}}
    steps:
      - uses: actions/checkout@v2

      - name: Check github ref
        id: github_ref
        run: |
          echo '${{ github.ref }}'
          if [[ "${{ github.ref }}" == refs/tags/v* ]]; then
            echo "found tags"
            echo '${ github.ref#refs/tags/ }'
          fi

      - uses: mukunku/tag-exists-action@v1.0.0
        id: checkTag
        with:
          tag: 'v1'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - id: set-matrix
        run: |
          echo ${{ steps.checkTag.outputs.exists }}
          if [ "${{ steps.checkTag.outputs.exists }}" = "true" ]; then
            echo "::set-output name=matrix::$(ls|jq -cnR '[inputs | select(length>0)]')"
          else
            echo "::set-output name=matrix::[\"one-test\"]"
          fi
  get:
    runs-on: ubuntu-20.04
    needs: set-matrix
    strategy:
      matrix:
        subdir: ${{fromJson(needs.set-matrix.outputs.matrix)}}
    steps:
      - run: echo ${{ matrix.subdir }}
        name: subdir
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  get-again:
    runs-on: ubuntu-20.04
    needs: set-matrix
    strategy:
      matrix:
        subdir: ${{fromJson(needs.set-matrix.outputs.matrix)}}
    steps:
      - run: echo ${{ matrix.subdir }}
        name: subdir
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
