name: output matrix
on:
  pull_request:
    branches:
      - main
  push:
    tags:
      - v*
    branches:
      - main
      - release-*
jobs:
  test_var:
    runs-on: ubuntu-20.04
    steps:
      - run: |
          velaux_version_clause=($(cat Makefile | grep "VELAUX_VERSION ?="))
          echo $velaux_version_clause
          VELAUX_VERSION=${velaux_version_clause[3]}
          echo $VELAUX_VERSION
          LDFLAGS="-s -w -X ${{ env.VELA_VERSION_KEY }}=${{ env.VELAD_VERSION }} -X ${{ env.VELAUX_VERSION_KEY }}=$VELAUX_VERSION -X ${{ env.VELAD_VERSION_KEY }}=${{ env.VELAD_VERSION }} -X ${{ env.VELA_GITVERSION_KEY }}=git-${{ env.VELA_SHA_SHORT }}"
          echo $LDFLAGS

  set-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{steps.set-matrix.outputs.matrix}}
    steps:
      - name: Set matrix
        id: set-matrix
        run: |
          if [[ "${{ github.ref }}" == refs/tags/v* ]]; then
            echo "pushing tag: ${{ github.ref_name }}"
            echo "::set-output name=matrix::[\"one-test\", \"two-test\"]"
          else
            echo "::set-output name=matrix::[\"one-test\"]"
          fi

  get:
    runs-on: ubuntu-20.04
    needs: set-matrix
    strategy:
      matrix:
        subdir: ${{fromJson(needs.set-matrix.outputs.matrix)}}
    steps:
      - run: echo ${{ matrix.subdir }}
        name: subdir
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  get-again:
    runs-on: ubuntu-20.04
    needs: set-matrix
    strategy:
      matrix:
        subdir: ${{fromJson(needs.set-matrix.outputs.matrix)}}
    steps:
      - run: echo ${{ matrix.subdir }}
        name: subdir
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
