name: output matrix
on:
  pull_request:
    branches:
      - main
  push:
    tags:
      - v*
    branches:
      - main
env:
  VELA_VERSION: 1.4.0
  VELA_VERSION2: 1.4.0-alpha.1
  VELA_VERSION3: 1.4.0-beta.2
jobs:

  set-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{steps.set-matrix.outputs.matrix}}
    steps:
      - name: Set matrix
        id: set-matrix
        run: |
          if [[ "${{ github.ref }}" == refs/tags/v* ]]; then
            echo "pushing tag: ${{ github.ref_name }}"
            echo "::set-output name=matrix::[\"one-test\", \"two-test\"]"
          else
            echo "::set-output name=matrix::[\"one-test\"]"
          fi

  get:
    runs-on: ubuntu-20.04
    needs: set-matrix
    strategy:
      matrix:
        subdir: ${{fromJson(needs.set-matrix.outputs.matrix)}}
    steps:
      - run: echo ${{ matrix.subdir }}
        name: subdir
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: echo "if 1"
        if: ${{ !contains(env.VELA_VERSION,'alpha') && !contains(env.VELA_VERSION,'beta')}}
      - run: echo "if 2"
        if: ${{ !contains(env.VELA_VERSION2,'alpha') && !contains(env.VELA_VERSION2,'beta')}}
      - run: echo "if 3"
        if: ${{ !contains(env.VELA_VERSION3,'alpha') && !contains(env.VELA_VERSION3,'beta')}}

  get-again:
    runs-on: ubuntu-20.04
    needs: set-matrix
    strategy:
      matrix:
        subdir: ${{fromJson(needs.set-matrix.outputs.matrix)}}
    steps:
      - run: echo ${{ matrix.subdir }}
        name: subdir
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  get-target:
    runs-on: ubuntu-20.04
    steps:
      - name: set_target
        run: |
          TARGETS=linux/amd64
          echo "OS=${TARGETS%/*}" 
          echo "ARCH=${TARGETS#*/}" 
          echo "OS=${TARGETS%/*}" >> $GITHUB_OUTPUT
          echo "ARCH=${TARGETS#*/}" >> $GITHUB_OUTPUT
      - name: get_target
        run: |
          echo ${{ env.OS }}
